### ISSUE TITLE
httpdirfs missing mountpoint parameter, rpi 4b 64bit

### ISSUE THREAD

**Issue by sdanfa** [fangfufu/httpdirfs#97]
Hello,
I can't get httpdirfs to work on a raspberry pi 4b, I got it working on my desktop ubuntu but on rpi it fails. I'm mounting for example at the end of the command with "/mnt". I saw a similar issue at bug report #62
Here's the error:

print_version: HTTPDirFS version 1.2.3
print_version: libcurl SSL engine: OpenSSL/1.1.1l
see httpdirfs -h for usage
fuse: missing mountpoint parameter

**Comment by fangfufu** [comment]
Your server's HTTP header does not provide content length. This software needs content length to work.

**Comment by mkurz** [comment]
Note for others, since it took me a while to figure out what's going on:
Just in case you are running on arm / aarch64 (e.g. Apple Silicon M1 / Asahi Linux) and run into:
`fuse: missing mountpoint parameter`
That is because the current httpdirfs release 1.2.3 is not compatible with arm / aarch64, see #103. A fix has been merged already: #104.
Here is a workaround for Arch Linux users, until a new release arrives: https://aur.archlinux.org/packages/httpdirfs#comment-880071
